Repository metal3-io/project-infra, pull requests merged in 2019-10, with the labels that each got.

#1 Add GCS configuration for job logs and first presubmit job.
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/M

#2 Configure config-updater plugin for prow configs.
  prow/config/plugins.yaml
Labels: size/XS

#3 Add OWNERS file.
  OWNERS
Labels: size/XS

#4 Add a shellcheck job for metal3-dev-env.
  prow/config/config.yaml
Labels: size/S

#5 Specify full path to shellcheck.
  prow/config/config.yaml
Labels: size/XS

#6 Use shellcheck script in metal3-dev-env.
  prow/config/config.yaml
Labels: size/S

#7 Always run shellcheck job on metal3-dev-env.
  prow/config/config.yaml
Labels: size/XS

#8 Enable tide for the project-infra repo.
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/S

#10 OWNERS: Add more approvers and reviewers.
  OWNERS
Labels: approved, lgtm, size/XS

#9 Makefile: Use prow checkconfig container for "make validate".
  prow/Makefile
Labels: approved, lgtm, size/XS

#11 Enable tide for metal3-dev-env.
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#13 Enable tide (merge automation) on all repos.
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#12 Pull in label_sync from openshift
  label_sync/BUILD.bazel
  label_sync/Makefile
  label_sync/README.md
  label_sync/cluster/label_sync_cron_job.yaml
  label_sync/cluster/label_sync_job.yaml
  label_sync/labels.css.tmpl
  label_sync/labels.md
  label_sync/labels.md.tmpl
  label_sync/labels.yaml
  label_sync/labels_example.yaml
  label_sync/main.go
  label_sync/main_test.go
  label_sync/syntax_error_example.yaml
Labels: approved, lgtm, size/XXL

#19 Revert "Pull in label_sync from openshift"
  label_sync/BUILD.bazel
  label_sync/Makefile
  label_sync/README.md
  label_sync/cluster/label_sync_cron_job.yaml
  label_sync/cluster/label_sync_job.yaml
  label_sync/labels.css.tmpl
  label_sync/labels.md
  label_sync/labels.md.tmpl
  label_sync/labels.yaml
  label_sync/labels_example.yaml
  label_sync/main.go
  label_sync/main_test.go
  label_sync/syntax_error_example.yaml
Labels: approved, size/XXL

#22 Add notes on how SSL certificates are managed.
  prow/README.md
Labels: approved, lgtm, size/S

#21 Add label_sync tool from kuberenetes to sync labels
  label_sync/.gitignore
  label_sync/Makefile
  label_sync/README.md
  label_sync/config_example.sh
  label_sync/labels.yaml
  label_sync/sync_labels.sh
Labels: approved, lgtm, size/L

#23 Add stbenjam to label_sync/OWNERS.
  label_sync/OWNERS
Labels: approved, lgtm, size/XS

#24 plank: Add job_url_prefix_config.
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#26 spyglass: Configure some artifact viewers.
  prow/config/config.yaml
Labels: approved, size/S

#27 spyglass: Fix lenses for viewing log files.
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#28 Add markdownlint job for metal3-dev-env.
  prow/config/config.yaml
Labels: approved, size/S

#29 Add CI jobs for cluster-api-provider-baremetal.
  prow/config/config.yaml
Labels: approved, size/M

#30 Disable 2 CAPBM jobs that aren't working yet.
  prow/config/config.yaml
Labels: approved, size/XS

#31 Use the capbm-unit image for the capbm unit job.
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#32 Always run the unit job for capbm.
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#33 Enable govet job by default in capbm
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#34 Add jobs for baremetal-operator
  prow/config/config.yaml
Labels: approved, lgtm, size/M

#36 Add a gosec job for baremetal-operator.
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#39 Separate unit test job for CAPBM v1alpha2
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#40 prow: Run barmetal-operator jobs by default.
  prow/config/config.yaml
Labels: approved, lgtm, size/S
