Repository metal3-io/project-infra, pull requests merged in 2020-07, with the labels that each got.

#122 Add kashifest and fmuyassarov as jenkins approvers
  jenkins/OWNERS
Labels: approved, lgtm, size/XS

#123 jenkins Unify vm flavors
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#127 Add code generation job for IPAM
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#129 Jenkins: fetch manifest at the of CI run
  jenkins/scripts/files/run_fetch_logs.sh
Labels: approved, lgtm, size/XS

#132 Jenkins: update integration test for CAPM3 v1a4 release
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/M

#133 Jenkins: Fix v1a4 jobs, and update CI description
  jenkins/README.md
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/S

#134 Update prow config for CAPM3 jobs
  prow/config/config.yaml
Labels: approved, size/XS
