Repository metal3-io/project-infra, pull requests merged in 2020-10, with the labels that each got.

#157 Reduce resouce size when using volume
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/S

#156 Fetch k8s logs post pivot
  jenkins/scripts/files/run_fetch_logs.sh
Labels: approved, lgtm, size/M

#155 Add retry conditions to volume creation and resizing steps
  jenkins/scripts/integration_test.sh
  jenkins/scripts/utils.sh
Labels: approved, lgtm, size/L

#160 Fix condition checking when volume status contains an error substring
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/utils.sh
Labels: approved, lgtm, size/XS

#161 Fix volume resizing in case of feature tests
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/S

#162 Update jenkins readme
  jenkins/README.md
Labels: approved, lgtm, size/M

#124 Upgrade golang containers to 1.15.3
  prow/config/config.yaml
Labels: approved, lgtm, size/S
