Repository metal3-io/project-infra, pull requests merged in 2020-05, with the labels that each got.

#79 prow: Add branch protection management
  prow/config/config.yaml
Labels: approved, lgtm, size/M

#81 prow: Fix branch protection for CAPM3
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#80 Use local images of BMO&CAMP3 for CI
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/S

#83 require the operator-sdk-generate job for baremetal-operator repository
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#86 Revert "require the operator-sdk-generate job for baremetal-operator repository"
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#87 add markdownlint job to metal3-docs repo
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#88 jenkins: Add fetching container logs from metal3-dev-env
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/files/run_clean.sh
  jenkins/scripts/files/run_fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test_clean.sh
Labels: approved, lgtm, size/L

#89 Add prow jobs for IPAM repo
  prow/config/config.yaml
Labels: approved, lgtm, size/M

#90 Rename metal3-io/metal3-ipam repo
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#91 jenkins: increase ubuntu node size to 6GB
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#92 rename metal3-io/metal3-ipam to metal3-io/ip-address-manager
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#93 Restore the operator-sdk-generate job on the baremetal-operator repository
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#82 Add prow test jobs for Hardware-classification-controller
  prow/config/config.yaml
Labels: approved, lgtm, ok-to-test, size/M

#94 jenkins: increase node memory to 8GB for Ubuntu deployments
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#96 jenkins: parameterize container runtime when fetching logs and increase disk size
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/files/run_fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/S

#95 add golint job for baremetal-operator repository
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#98 jenkins: Update doc and remove unused variable
  jenkins/README.md
  jenkins/jobs/integration_tests.pipeline
Labels: approved, lgtm, size/S

#97 Add some details on who can run each prow command.
  prow/README.md
Labels: approved, lgtm, size/S

#78 prow: Update use of deprecated config entry
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#99 Start working on Prow upgrades
  clusters/ci/imagepruner.yaml
  prow/config/config.yaml
  prow/manifests/deck-deployment.yaml
  prow/manifests/hook-deployment.yaml
  prow/manifests/horologium-deployment.yaml
  prow/manifests/plank-deployment.yaml
  prow/manifests/sinker-deployment.yaml
  prow/manifests/statusreconciler-deployment.yaml
  prow/manifests/tide-deployment.yaml
Labels: approved, lgtm, size/XL

#100 prow: Fix a prow config path typo
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#101 prow: Fix path to github auth token
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#102 prow: Fix github org in prow autobump job
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#105 Address issues encountered with prow upgrade
  prow/config/config.yaml
  prow/manifests/deck-deployment.yaml
  prow/manifests/hook-deployment.yaml
  prow/manifests/horologium-deployment.yaml
  prow/manifests/plank-deployment.yaml
  prow/manifests/sinker-deployment.yaml
  prow/manifests/statusreconciler-deployment.yaml
  prow/manifests/tide-deployment.yaml
Labels: approved, lgtm, size/M
