Repository metal3-io/project-infra, pull requests merged in 2020-09, with the labels that each got.

#140 CI: remove extra quotes
  jenkins/scripts/files/run_fetch_logs.sh
Labels: approved, lgtm, size/XS

#143 Jenkins: Increase integration CI timeout
  jenkins/jobs/integration_tests.pipeline
Labels: approved, lgtm, size/XS

#141 CI: fetch upgrade logs to the archive
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/files/run_fetch_logs.sh
Labels: approved, lgtm, size/S

#144 Jenkins: revert #143
  jenkins/jobs/integration_tests.pipeline
Labels: approved, lgtm, size/XS

#145 Jenkins: fix upgrade test caller
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#146 Jenkins: Fix conditional statement
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#148 prow: run gomod.sh as a presubmit
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#150 Add compulsory integration test for IPAM repo
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#149 Add support for IPAM testing
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#151 update go images for baremetal-operator jobs
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#147 Jenkins: Use Ubuntu volume instead of image
  jenkins/scripts/integration_clean.sh
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/L

#153 Fix volume deletion
  jenkins/scripts/integration_clean.sh
Labels: approved, lgtm, size/XS

#154 Remove --force delete from volume deletion
  jenkins/scripts/integration_clean.sh
Labels: approved, lgtm, size/XS
