Repository metal3-io/project-infra, pull requests merged in 2020-03, with the labels that each got.

#58 Jenkins: add cleanup pipeline and script
  jenkins/jobs/integration_tests_clean.pipeline
  jenkins/scripts/integration_clean.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/L

#43 Add a kind/ci label
  label_sync/labels.yaml
Labels: approved, kind/ci, lgtm, size/XS

#57 Jenkins: Rename CAPBM to CAPM3
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#60 Add periodic jobs for marking old issues stale
  label_sync/labels.yaml
  prow/config/config.yaml
Labels: approved, lgtm, size/M

#61 Update secret name
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#59 Update CI doc based on #58
  jenkins/README.md
Labels: approved, lgtm, size/XS

#63 Add cluster-api-provider-metal3 repo in Prow and Jenkins config
  jenkins/README.md
  jenkins/scripts/files/run_integration_tests.sh
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: approved, lgtm, size/M

#64 Jenkins e2e test is v1a3 by default
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#66 Merge the PR on target branch before starting the test
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/M

#62 Update Jenkins CI doc
  jenkins/README.md
Labels: approved, lgtm, size/XS

#67 Jenkins fix condition to avoid merge
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#69 Jenkins reducing cores to 4 for test vms
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#70 Update Jenkins doc
  jenkins/README.md
Labels: approved, lgtm, size/XS
