Repository metal3-io/project-infra, pull requests merged in 2020-06, with the labels that each got.

#108 Jenkins, fetch m3-dev-env console logs during log gathering
  jenkins/scripts/files/run_fetch_logs.sh
Labels: approved, lgtm, size/XS

#107 Jenkins: Add conditions to trigger pivot/upgrade/remediation tests
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/M

#111 Add CAPM3 jobs and remove CAPBM jobs
  prow/config/config.yaml
Labels: approved, lgtm, size/M

#109 jenkins: Increase VM resources for feature_tests
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#110 Jenkins: do not build BMO and CAPM3 images for each m3-dev-env PRs
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/M

#112 Jenkins re-enable BMO image building for master jobs
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#113 Jenkins: use random characters in vm names
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/integration_clean.sh
Labels: approved, lgtm, size/XS

#114 Jenkins: fix wrong condition for master runs
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#115 Increase timeout for feature test
  jenkins/jobs/integration_tests.pipeline
Labels: approved, lgtm, size/XS

#116 prow: Use OWNERS file to determine reviewers
  prow/config/plugins.yaml
Labels: approved, lgtm, size/XS

#117 Remove unnecessary vars Update default memory
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#118 Jenkins: reduce nodes memory to 4GB
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, do-not-merge/hold, size/XS

#120 Jenkins: fix name issue in cleanup script
  jenkins/scripts/integration_clean.sh
Labels: approved, lgtm, size/XS

#121 Add ServerAliveCountMax for ssh connection
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#119 Jenkins: reduce VM RAM size to 10 / 16 GB
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS
