Repository metal3-io/project-infra, pull requests merged in 2020-04, with the labels that each got.

#72 Jenkins: Use CentOS for target cluster for CentOS metal3-dev-env
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/M

#71 Replaces management cluster in CI when CI host is Ubuntu
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#73 :bug: Temporarily disabling kind usage as management cluster
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#74 Remove v1alpha1 integration test caller
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#75 Enable kind in CI after metal3-dev-env #293
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#76 Add GITHUB_TOKEN needed with clusterctl access to Github
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#77 add job to check operator-sdk generation for baremetal-operator
  prow/config/config.yaml
Labels: approved, lgtm, size/S
