Repository metal3-io/project-infra, pull requests merged in 2021-05, with the labels that each got.

#184 Fetch also exited container logs
  jenkins/scripts/files/run_fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#182 Upgrade prow setup
  README.md
  clusters/ci/README.md
  clusters/ci/imagepruner.yaml
  clusters/ci/ssl/certificate.yaml
  label_sync/labels.yaml
  prow/Makefile
  prow/README.md
  prow/config/config.yaml
  prow/config/plugins.yaml
  prow/images/webhook.png
  prow/manifests/config_configmap.yaml
  prow/manifests/crier_deployment.yaml
  prow/manifests/crier_rbac.yaml
  prow/manifests/deck-deployment.yaml
  prow/manifests/deck_deployment.yaml
  prow/manifests/deck_rbac.yaml
  prow/manifests/deck_service.yaml
  prow/manifests/ghproxy.yaml
  prow/manifests/hook-deployment.yaml
  prow/manifests/hook_deployment.yaml
  prow/manifests/hook_rbac.yaml
  prow/manifests/hook_service.yaml
  prow/manifests/horologium-deployment.yaml
  prow/manifests/horologium_deployment.yaml
  prow/manifests/horologium_rbac.yaml
  prow/manifests/ingress.yaml
  prow/manifests/namespace.yaml
  prow/manifests/needs-rebase_deployment.yaml
  prow/manifests/needs-rebase_service.yaml
  prow/manifests/plank-deployment.yaml
  prow/manifests/plugins_configmap.yaml
  prow/manifests/prow_controller_manager_deployment.yaml
  prow/manifests/prow_controller_manager_rbac.yaml
  prow/manifests/prowjob_customresourcedefinition.yaml
  prow/manifests/sinker-deployment.yaml
  prow/manifests/sinker_deployment.yaml
  prow/manifests/sinker_rbac.yaml
  prow/manifests/statusreconciler-deployment.yaml
  prow/manifests/statusreconciler_deployment.yaml
  prow/manifests/statusreconciler_rbac.yaml
  prow/manifests/tide-deployment.yaml
  prow/manifests/tide_deployment.yaml
  prow/manifests/tide_rbac.yaml
  prow/manifests/tide_service.yaml
  prow/persistent_volume.yaml
  prow/ssl/README.md
  prow/ssl/cluster-issuer.yaml
Labels: approved, lgtm, size/XXL

#185 Remove duplication in external plugins
  prow/config/plugins.yaml
Labels: approved, lgtm, size/S

#186 Don't use prow image autobump
  prow/config/config.yaml
Labels: approved, lgtm, size/M

#188 Jenkins: Update configuration document
  jenkins/README.md
  jenkins/images/jenkins_ui.png
  jenkins/images/status.png
Labels: approved, lgtm, size/L

#191 Increase feature tests timeout in CI
  jenkins/jobs/integration_tests.pipeline
Labels: approved, lgtm, size/XS

#190 disable automatic self-approval and ensure 2 lgtm does not approve
  prow/config/plugins.yaml
Labels: approved, lgtm, size/S

#192 Move sushy-tools & vbmc to ironic-image repo
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS
