Repository metal3-io/project-infra, pull requests merged in 2021-06, with the labels that each got.

#193 Remove ironic-inspector-image related config
  jenkins/scripts/files/run_integration_tests.sh
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: approved, lgtm, size/XS

#198 Add .cluster-api config to fetch logs tarball
  jenkins/scripts/files/run_fetch_logs.sh
Labels: approved, lgtm, size/XS

#199 Add Feruzjon as approver
  OWNERS
Labels: approved, lgtm, size/XS

#202 Add colors to Ansible output in Jenkins
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#203 ✨ Add required test triggering contexts for v1a4 and v1a5
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#201 Remove V1alpha3 instances and modify V1alpha4 branch for CAPM3.
  jenkins/README.md
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/S

#205 🐛 Change status checks for master and release branches in CAPM3/IPAM
  prow/config/config.yaml
Labels: approved, lgtm, size/XS

#200 Add Furkat as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#207 Change integration test status check
  prow/config/config.yaml
Labels: approved, lgtm, size/S

#204 📖 Change test trigger commands
  jenkins/README.md
Labels: approved, lgtm, size/XS

#209 Build local images of CAPM3 and IPAM in dev-env patches
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/S

#210 Jenkins: Revert #209
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/S

#211 :bug: Fix closing for condition
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/XS

#212 Update DockerHub registry path
  prow/config/config.yaml
Labels: approved, lgtm, size/M

#208 Handle e2e tests in integration test scripts
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#214 :bug: Fix quotes around TEST_FOR var
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#215 Jenkins: Fix missing S in the condition
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS

#216 Use larger VM volume for e2e tests
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XS
