Repository metal3-io/project-infra, pull requests merged in 2021-12, with the labels that each got.

#283 Increase VM storage volume size
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#281 Shrink syslog file size in BML
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
Labels: size/XS, approved, lgtm

#285 ✨Add presubmit prow jobs for CAPM3 release-0.5/0.4 branches
  prow/config/config.yaml
Labels: approved, lgtm, size/L

#287 Switch to docker.io/golang:1.16 image in capm3 tests
  prow/config/config.yaml
Labels: approved, lgtm, size/L

#288 Prow: Fix naming of generate job
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#286 Add mariadb-image to prow & Jenkins
  jenkins/scripts/files/run_integration_tests.sh
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/XS, approved, lgtm

#290 Increase frequency of running go based CI jobs
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#292 Improve BML cleaning
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
Labels: size/M, approved, lgtm

#293 Remove master branch reference for BMO
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#296 Remove master reference in BML pipeline and comments
  jenkins/README.md
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_clean.sh
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test_clean.sh
Labels: size/S, approved, lgtm

#297 Switch to main in project-infra references
  jenkins/README.md
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/integration_tests_clean.pipeline
Labels: size/S, approved, lgtm

#298 📖 Update jenkins readme
  jenkins/README.md
Labels: size/S, approved, lgtm

#299 Disable concurrent builds in BML
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/scripts/bare_metal_lab/README.md
Labels: size/S, approved, lgtm

#294 Set same variables for BML as for other pipelines
  jenkins/scripts/bare_metal_lab/README.md
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
  jenkins/scripts/bare_metal_lab/files/config.sh
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_env.sh
Labels: approved, lgtm, size/L
