Repository metal3-io/project-infra, pull requests merged in 2021-09, with the labels that each got.

#223 Fetch atop and sysstat metrics
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/XS, approved, lgtm

#222 Don't download IPA in integration tests
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#224 Set Kubernetes Version to v1.21.2 for v1a4 jobs
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#225 append variables to vars.sh file without emptying the file
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#226 Fix the location of k8s version export
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#228 exports IMAGE_LOCATION and IMAGE_NAME variables for airship-dev-tools integration test
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#232 Remove KUBERNETES_VERSION var
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#229 Update Prow
  label_sync/.gitignore
  label_sync/Makefile
  label_sync/OWNERS
  label_sync/README.md
  label_sync/config_example.sh
  label_sync/sync_labels.sh
  prow/Makefile
  prow/config/config.yaml
  prow/config/external-plugins/needs-rebase_deployment.yaml
  prow/config/external-plugins/needs-rebase_service.yaml
  prow/config/labels.yaml
  prow/manifests/config_configmap.yaml
  prow/manifests/crier_deployment.yaml
  prow/manifests/crier_rbac.yaml
  prow/manifests/deck_deployment.yaml
  prow/manifests/deck_rbac.yaml
  prow/manifests/deck_service.yaml
  prow/manifests/ghproxy.yaml
  prow/manifests/hook_deployment.yaml
  prow/manifests/hook_rbac.yaml
  prow/manifests/hook_service.yaml
  prow/manifests/horologium_deployment.yaml
  prow/manifests/horologium_rbac.yaml
  prow/manifests/ingress.yaml
  prow/manifests/labels_cronjob.yaml
  prow/manifests/namespace.yaml
  prow/manifests/needs-rebase_deployment.yaml
  prow/manifests/persistent_volume.yaml
  prow/manifests/plugins_configmap.yaml
  prow/manifests/prow_controller_manager_deployment.yaml
  prow/manifests/prow_controller_manager_rbac.yaml
  prow/manifests/prowjob_customresourcedefinition.yaml
  prow/manifests/sinker_deployment.yaml
  prow/manifests/sinker_rbac.yaml
  prow/manifests/starter.yaml
  prow/manifests/statusreconciler_rbac.yaml
  prow/manifests/tide_deployment.yaml
  prow/manifests/tide_rbac.yaml
  prow/manifests/tide_service.yaml
Labels: approved, lgtm, size/XXL

#233 Bug: fix incorrect namespace in the prow configMap
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#196 Add scripts for Bare Metal Lab Jenkins runs
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/scripts/bare_metal_lab/README.md
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
  jenkins/scripts/bare_metal_lab/files/config.sh
  jenkins/scripts/bare_metal_lab/files/reset_network.sh
  jenkins/scripts/bare_metal_lab/templates/bmhosts_crs.yaml.j2
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/XL
