Repository metal3-io/project-infra, pull requests merged in 2021-11, with the labels that each got.

#262 Don't enable push-gateway in ghProxy
  prow/manifests/starter.yaml
Labels: size/XS, approved, lgtm

#261 Improve export vars for local images
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#264 Jenkins: remove conditionals around REPO_BRANCH
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#267 Make v1a5 centos job required in m3-dev-env repo
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#268 Bare Metal lab integration test improvement
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
  jenkins/scripts/bml_integration_test.sh
Labels: size/S, approved, lgtm

#270 Add release master JJBs to FRA1
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#271 Add release to master CI tests files
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/integration_clean.sh
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test_clean.sh
Labels: size/S, approved, lgtm

#273 Fix integration cleanup file to add cleanup step for FRA1
  jenkins/scripts/integration_clean.sh
Labels: size/S, approved, lgtm

#272 Run e2e tests in FRA1
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/integration_clean.sh
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_clean.sh
Labels: size/S, approved, lgtm

#227 Fetch Prometheus data from management cluster
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#275 Prow: add cherrypicker external plugin
  prow/config/external-plugins/cherrypicker_deployment.yaml
  prow/config/external-plugins/cherrypicker_service.yaml
  prow/config/plugins.yaml
Labels: approved, lgtm, size/L

#274 Re-configure label synchronization CronJob
  prow/Makefile
  prow/manifests/labels_cronjob.yaml
Labels: size/S, approved, lgtm

#276 Add labels.yaml to config_updater
  prow/config/plugins.yaml
Labels: size/XS, approved, lgtm

#278 Add smoshiur1237 as a reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#277 Fix a bug with jsonpath during log fetching
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/XS, approved, lgtm

#280 Prepare for BMO main branch switch
  jenkins/scripts/bare_metal_lab/files/config.sh
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#279 Fix unbound prometheus monitoring variable issue
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#269 Avoid unnecessary CI jobs
  prow/config/config.yaml
Labels: size/M, approved, lgtm

#282 Fix syntax issues in log fetching script
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/M, approved, lgtm
