Repository metal3-io/project-infra, pull requests merged in 2022-02, with the labels that each got.

#336 Remove master branch ref for ironic-image and ironic- ipa-downloader
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#325 Fix UPGRADE_TEST unbound variable issue in BML
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/scripts/bml_integration_test.sh
Labels: size/XS, approved, lgtm

#338 Rename airship to metal3 in repos and jjb
  jenkins/README.md
  jenkins/scripts/bare_metal_lab/README.md
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/S, approved, lgtm

#339 Update CI jenkins image
  jenkins/README.md
  jenkins/images/jenkins_metal3_view.png
  jenkins/images/jenkins_ui.png
Labels: size/XS, approved, lgtm

#335 Remove TARGET_NODE_OS variable
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#342 📖 Remove prebaked volume notes from jenkins notes
  jenkins/README.md
Labels: size/S, approved, lgtm

#341 Use metal3ci user for CI runs
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/integration_tests_clean.pipeline
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/S, approved, lgtm

#340 :seedling: Remove russellb as active approver
  OWNERS
Labels: size/XS, approved, lgtm

#343 Change the BML to use node 6 as a provisioned node
  jenkins/scripts/bare_metal_lab/templates/bmhosts_crs.yaml.j2
Labels: size/S, approved, lgtm

#344 Remove DISTRIBUTION var and use IMAGE_OS instead
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/files/run_clean.sh
  jenkins/scripts/files/run_fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_clean.sh
Labels: size/M, approved, lgtm

#347 Rename prefix of OpenStack networks from airship to metal3
  jenkins/scripts/utils.sh
Labels: size/XS, approved, lgtm

#345 Use the metal3ci user for BML jobs
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/XS, approved, lgtm

#348 Update Jenkins worker name to metal3-static-workers
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/integration_tests_clean.pipeline
Labels: size/XS, approved, lgtm

#349 Include ubuntu in status checks
  jenkins/README.md
  prow/config/config.yaml
Labels: size/M, approved, lgtm

#350 switch to use new ci user references
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/integration_tests_clean.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_clean.sh
  jenkins/scripts/utils.sh
Labels: size/M, approved, lgtm

#352 Update souce cluster OS images to metal3* from airship*
  jenkins/scripts/utils.sh
Labels: size/XS, approved, lgtm

#354 🐛 Fix TESTS_FOR value check for ubuntu feature tests
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm
