Repository metal3-io/project-infra, pull requests merged in 2022-01, with the labels that each got.

#300 Create/delete floating IP in Fra1
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/utils.sh
Labels: size/S, approved, lgtm

#302 Add m3-dev-env main branch referenc in prow/config
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#304 Add e2e tested_repo _artifacts dir to logs tarball
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/XS, approved, lgtm

#303 Remove Prometheus database dump fetch
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#306 Add main branch reference for ironic-image and IPA-downloader repo
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#309 Allow pass through of CAPI and CAPM3 release variables
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#311 Fix unbound variable use logic
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#301 Allow keeping tester VM for 24 hours
  jenkins/README.md
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/integration_clean.sh
  jenkins/scripts/integration_test.sh
Labels: size/M, approved, lgtm

#312 🌱 Move maelk to emeritus_approvers list
  OWNERS
Labels: size/XS, approved, lgtm

#308 Add export K8s version for airship integration tests
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#314 ✨ Add transfer-issue plugin to Prow
  prow/config/plugins.yaml
  prow/manifests/starter.yaml
Labels: size/XS, approved, lgtm

#307 Allow adding triage labels on issues across Metal3.io
  prow/config/labels.yaml
  prow/config/plugins.yaml
Labels: size/M, approved, lgtm

#313 🐛 Remove leftover volume related helper functions
  jenkins/scripts/utils.sh
Labels: size/M, approved, lgtm

#319 🐛 Prow: Remove additional blank space from prow config file
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#321 🌱 Add UPGRADE_TEST var export for e2e upgrade tests
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#323 Default UPGRADE_TEST to false
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#331 Prow: Add missing require-matching-label plugin to plugins list
  prow/config/plugins.yaml
  prow/manifests/starter.yaml
Labels: size/XS, approved, lgtm
