Repository metal3-io/project-infra, pull requests merged in 2022-06, with the labels that each got.

#389 Fix fetching e2e logs
  jenkins/scripts/files/run_fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/S, approved, lgtm

#400 Fix capm3 cleaning issue
  jenkins/scripts/files/run_clean.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test_clean.sh
  jenkins/scripts/integration_test_env.sh
Labels: size/M, approved, lgtm

#402 Fix running integration tests from capm3
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#403 Add verbosity to bm lab integration test
  jenkins/scripts/bml_integration_test.sh
Labels: size/XS, approved, lgtm

#405 Update the name of BMHs in CRs
  jenkins/scripts/bare_metal_lab/templates/bmhosts_crs.yaml.j2
Labels: size/XS, approved, lgtm

#404 BML: Clone metal3-dev-env to correct folder
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/M, approved, lgtm

#408 BML: Accept repo name over ssh
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
Labels: size/XS, approved, lgtm

#409 Use ginkgo focus instead of boolean
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#410 Fix ginkgo_focus null string value
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm
