Repository metal3-io/project-infra, pull requests merged in 2022-07, with the labels that each got.

#411 Fix k8s version to 1.23.x for v1alpha5
  jenkins/scripts/files/run_integration_tests.sh
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#412 🌱 Remove CAPM3 v1alpha4 related logic from the code
  jenkins/README.md
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test_env.sh
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#407 Fetch init container logs
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/XS, approved, lgtm

#414 Uplift k8s to v1.23.8
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#413 BML: Merge the updated repo/branch with the target
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
Labels: size/S, approved, lgtm

#415 Prow: Rename trigger phrases in CI
  jenkins/README.md
  prow/config/config.yaml
Labels: size/M, approved, lgtm

#417 🐛 Prow: Add missing branch name configuration for mariadb-image repo
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#418 Propagate CAPM3RELEASEBRANCH from jjb to pipeline and scripts
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_env.sh
Labels: size/S, approved, lgtm

#419 Add mohammed as reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#420 Add main branch centos test as required for metal3-dev-env
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#422 🐛 Use go1.17 for release-1.1 branch ProwJobs same as for main branch
  prow/config/config.yaml
Labels: size/S, approved, lgtm
