Repository metal3-io/project-infra, pull requests merged in 2022-04, with the labels that each got.

#371 Revert "Temporary fix while Nordix registry is down"
  jenkins/scripts/integration_test_env.sh
Labels: size/XS, approved, lgtm

#372 Run BML test with updated code on metal3-dev-env.
  jenkins/scripts/bare_metal_lab/deploy-lab.yaml
  jenkins/scripts/bml_integration_test.sh
Labels: size/S, approved, lgtm

#370 add ironic-image testing pipeline
  jenkins/jobs/ironic_image_build_test.pipeline
  jenkins/scripts/ironic_build_test.sh
  jenkins/scripts/ironic_image_build_test_delete.sh
  jenkins/scripts/start_ironic_image_build_test.sh
Labels: approved, lgtm, size/L

#373 enable ironic source install for integration tests
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#376 fix ironic source install in integration tests
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#375 Remove workaround for "no-space" issue
  jenkins/scripts/integration_test.sh
  jenkins/scripts/utils.sh
Labels: size/M, approved, lgtm
