Repository metal3-io/project-infra, pull requests merged in 2023-05, with the labels that each got.

#514 Add e2e integration as required job for release-1.4 branch
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#515 Prow synchronize images
  prow/manifests/overlays/metal3/config.yaml
  prow/manifests/overlays/metal3/kustomization.yaml
Labels: size/M, approved, lgtm

#517 Run e2e on default region
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_clean.sh
Labels: size/S, approved, lgtm

#503 add shellcheck to ironic-image
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#518 Prow: Bump ingress-nginx to v1.7.1
  prow/infra/ingress-controller-job-patch.yaml
  prow/infra/kustomization.yaml
Labels: size/S, approved, lgtm

#519 Modify integration test to start with ci_run make target
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#522 Merge SKIP_CLEANUP and SKIP_DELETION variables
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/M, approved, lgtm

#523 Remove GINKGO_SKIP variable from project infra
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#524 Revert "Run e2e on default region"
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_clean.sh
Labels: size/S, approved, lgtm

#525 add shellcheck
  hack/shellcheck.sh
  jenkins/scripts/bml_cleanup.sh
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/files/run_clean.sh
  jenkins/scripts/files/run_fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_clean.sh
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_clean.sh
  jenkins/scripts/integration_test_env.sh
  jenkins/scripts/ironic_build_test.sh
  jenkins/scripts/ironic_image_build_test_delete.sh
  jenkins/scripts/start_ironic_image_build_test.sh
  jenkins/scripts/utils.sh
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/XXL

#529 Drop CAPM3 release-1.1 CI support
  jenkins/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#520 Prow: Upgrade cluster to v1.26.4 and document
  prow/README.md
  prow/capo-cluster/kubeadmcontrolplane.yaml
  prow/capo-cluster/machinedeployment.yaml
  prow/capo-cluster/openstackmachinetemplates.yaml
Labels: approved, lgtm, size/L

#527 Prow: Upgrade k8s to v1.26.5
  prow/capo-cluster/kubeadmcontrolplane.yaml
  prow/capo-cluster/machinedeployment.yaml
  prow/capo-cluster/openstackmachinetemplates.yaml
  prow/cluster-resources/kustomization.yaml
Labels: size/S, approved, lgtm

#526 add markdownlint for ironic-ipa-downloader
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#531 e2e integeration fix
  jenkins/scripts/integration_test_env.sh
Labels: size/XS, approved, lgtm
