Repository metal3-io/project-infra, pull requests merged in 2023-08, with the labels that each got.

#560 Add describe pods output during log collection
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/S, approved, lgtm

#562 re-enable IPA download in tests
  jenkins/scripts/integration_test_env.sh
Labels: size/XS, approved, lgtm

#551 Bump golang version to v1.20 for bmo main branch prow tests
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#565 Prow: Bump ingress-nginx and calico versions
  prow/cluster-resources/kustomization.yaml
  prow/infra/kustomization.yaml
Labels: size/XS, approved, lgtm

#566 Rename DEFAULT_HOSTS_MEMORY variable name
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#558 Fix make target for dev-env PRs
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#563 Spread tests across projects and regions in cloud
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/integration_clean.sh
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_clean.sh
  jenkins/scripts/ironic_image_build_test_delete.sh
Labels: size/M, approved, lgtm

#559 Remove mentions of ansible based feature tests
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#568 Add release-1.5 branch configurations
  jenkins/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#567 Update iLO IP of replaced host
  jenkins/scripts/bare_metal_lab/default_vars/vars.yaml
  jenkins/scripts/bare_metal_lab/tasks/cleanup-tasks.yaml
Labels: size/XS, approved, lgtm

#569 Prow: Disable ghproxy pushgateway
  prow/manifests/base/ghproxy.yaml
Labels: size/XS, approved, lgtm
