Repository metal3-io/project-infra, pull requests merged in 2023-02, with the labels that each got.

#477 📖 Document external prow plugins in the README
  jenkins/README.md
Labels: size/S, approved, lgtm

#479 Enhance prow readme with enabling prow in new repo howto
  prow/README.md
  prow/images/green_webhook.png
  prow/images/metal3-io-bot.png
Labels: size/S, approved, lgtm

#480 Fix trigger command for jenkins job in doc
  jenkins/README.md
Labels: size/S, approved, lgtm

#481 Add SKIP_CLEANUP variable for e2e tests
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#472 Move ephemeral cluster from jumphost to internal server
  jenkins/scripts/bml_cleanup.sh
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/fetch_logs.sh
Labels: size/M, approved, lgtm

#482 Add SKIP_CLEANUP variable for BML integration test
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/scripts/bml_integration_test.sh
Labels: size/XS, approved, lgtm

#484 prow: uplift go in ipam release-1.2 branch to 1.18
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#485 update user-guide url
  SECURITY_CONTACTS
Labels: size/XS, approved, lgtm

#483 Add lentzi90 as an approver
  OWNERS
Labels: size/XS, approved, lgtm

#486 prow: add metal3-io/.github to prow
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/XS, approved, lgtm

#487 Fix serial port log collection in bml
  jenkins/scripts/bare_metal_lab/tasks/deploy-tasks.yaml
Labels: size/XS, approved, lgtm

#475 🌱 Add e2e integration as required checks
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#488 Fix cleaning up ephemeral cluster after successful run in bml
  jenkins/scripts/bml_cleanup.sh
Labels: size/XS, approved, lgtm
