Repository metal3-io/project-infra, pull requests merged in 2023-07, with the labels that each got.

#553 Revert "Enable mariadb instead of SQLite"
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#550 Bump golang to v1.20 for ipam main branch prow tests
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#549 Fixes confusing log placements on failing runs.
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/S, approved, lgtm

#554 Changed e2e basic test flavor
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#556 Add @mboukhalfa and @tuminoid as approvers
  OWNERS
Labels: size/XS, approved, lgtm

#548 Fix 6hr timeout on e2e integration tests
  jenkins/jobs/integration_tests.pipeline
Labels: size/XS, approved, lgtm

#555 Remove golangci-lint prow test for IPAM main branch
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm
