Repository metal3-io/project-infra, pull requests merged in 2023-10, with the labels that each got.

#584 increase ssh inactivity tolerance in test jobs
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#585 Add BMORELEASEBRANCH variable
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#586 Uplift prow container images
  prow/Makefile
  prow/manifests/overlays/metal3/config.yaml
  prow/manifests/overlays/metal3/kustomization.yaml
Labels: size/M, approved, lgtm

#588 Add latest image tag in configuration
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#589 Update prow config to k8s 1.27
  prow/README.md
  prow/capo-cluster/kubeadmcontrolplane.yaml
  prow/capo-cluster/machinedeployment.yaml
  prow/capo-cluster/openstackmachinetemplates.yaml
Labels: approved, lgtm

#590 Prow: Fix commenter and checkconfig command
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#587 Bump cloud-provider-openstack to 1.28.0
  prow/cluster-resources/kustomization.yaml
Labels: size/S, approved, lgtm

#591 Prow: Update ingress-nginx to v1.9.4
  prow/infra/add-args.yaml
  prow/infra/configmap-patch.yaml
  prow/infra/kustomization.yaml
Labels: size/S, approved, lgtm
