Repository metal3-io/project-infra, pull requests merged in 2023-12, with the labels that each got.

#600 run markdownlint when changing the linter
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#599 Add metal3-io/community repository in prow config
  prow/manifests/overlays/metal3/config.yaml
  prow/manifests/overlays/metal3/plugins.yaml
Labels: size/M, approved, lgtm

#601 bump markdownlint to 0.13.0
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#603 bump gosec to 2.18.2
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#604 Add config for ironic-image release-23.1
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#609 use correct variable name for Ironic local build
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#608 Add jenkins-operator for prow
  prow/.gitignore
  prow/README.md
  prow/manifests/overlays/metal3/config.yaml
  prow/manifests/overlays/metal3/external-plugins/jenkins-operator.yaml
  prow/manifests/overlays/metal3/kustomization.yaml
  prow/manifests/overlays/metal3/patches/jenkins-operator.yaml
Labels: approved, lgtm, size/L

#610 BMO e2e: Allow flexible artifact naming
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/XS, approved, lgtm
