Repository metal3-io/project-infra, pull requests merged in 2023-01, with the labels that each got.

#462 move from kubeval to kubeconform
  prow/config/config.yaml
Labels: approved, lgtm, size/XXL

#463 remove hwcc from prow
  prow/config/config.yaml
Labels: size/M, approved, lgtm

#464 .github: secure github actions
  .github/workflows/yamllint.yaml
Labels: size/XS, approved, lgtm

#466 prow: use images from docker.io
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#467 pin gosec with version and digest
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#468 add tuminoid to reviewers
  OWNERS
Labels: size/XS, approved, lgtm

#461 Add prow test for Nordix/metal3-dev-tools
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: approved, lgtm, size/L

#465 Prow: Add build-e2e job for CAPM3
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#474 prow: cleanup archived repos
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/XS, approved, lgtm

#473 Add prow setup for Nordix metal3-dev-tools and metal3-clusterapi-docs repo
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: size/M, approved, lgtm

#476 Add Nordix/ org in tide config and modify merge_method to 'rebase' for Nordix repos
  prow/config/config.yaml
Labels: size/XS, approved, lgtm
