Repository metal3-io/project-infra, pull requests merged in 2023-04, with the labels that each got.

#499 Change bridge name to external, after renaming it in metal3-dev-env
  jenkins/scripts/bare_metal_lab/tasks/deploy-tasks.yaml
Labels: size/XS, approved, lgtm

#501 add markdownlint linter and fix markdown issues
  README.md
  hack/markdownlint.sh
  jenkins/README.md
  jenkins/scripts/bare_metal_lab/README.md
  prow/README.md
  prow/config/config.yaml
  prow/ssl/README.md
Labels: approved, lgtm, size/XL

#502 add basic linters to ihwir
  prow/config/config.yaml
Labels: size/M, approved, lgtm

#504 Fix unsetting NUM_NODES variable and passing it to BML
  jenkins/scripts/bare_metal_lab/default_vars/vars.yaml
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#506 Set default value for IRONIC_USE_MARIADB
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#505 Refactor target log collection script
  jenkins/scripts/files/run_fetch_logs.sh
Labels: size/XS, approved, lgtm

#507 Remove BMOBRANCH export
  jenkins/scripts/integration_test_env.sh
Labels: size/XS, approved, lgtm

#511 Propagate UPGRADE_FROM_RELEASE to capm3
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: approved, lgtm, size/L

#512 add markdownlint for ironic-image
  prow/config/config.yaml
Labels: size/S, approved, lgtm

#513 Prow: Cleanup old config
  prow/config/config.yaml
  prow/config/plugins.yaml
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/XXL

#496 Add release-1.4 branch configurations for CAPM3/IPAM repos
  jenkins/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm
