Repository metal3-io/project-infra, pull requests merged in 2024-06, with the labels that each got.

#778 Make BMO e2e tests optional
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#780 Remove BMO unit jobs
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#781 Changes related to rebuilding the Prow cluster
  prow/README.md
  prow/capo-cluster/openstackcluster.yaml
  prow/infra/service.yaml
Labels: size/S, approved, lgtm

#782 Move Prow to Xerces
  prow/README.md
  prow/capo-cluster/infra-md.yaml
  prow/capo-cluster/kubeadmcontrolplane.yaml
  prow/capo-cluster/machinedeployment.yaml
  prow/capo-cluster/openstackcluster.yaml
  prow/capo-cluster/openstackmachinetemplates.yaml
  prow/infra/service.yaml
  prow/manifests/base/hook.yaml
Labels: approved, lgtm, size/L

#783 bump go 1.22 for ironic-standalone-operator
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#785 remove BMO e2e tests from Prow
  jenkins/jobs/bmo_e2e_tests.pipeline
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#786 Update config for ironic-image release-25.0
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#793 Prow cleanup and use DNS hook.
  prow/manifests/base/hook.yaml
Labels: size/XS, approved, lgtm

#779 implement dynamic fullstack builder pipeline
  jenkins/jobs/dynamic_fullstack_building.pipeline
  jenkins/scripts/artifactory/utils.sh
  jenkins/scripts/dynamic_worker_workflow/build_ipa.sh
  jenkins/scripts/dynamic_worker_workflow/fullstack.sh
  jenkins/scripts/dynamic_worker_workflow/fullstack_build_ironic.sh
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/cleanup-package/post-install.d/99-cleanup-package
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-add-buildinfo/install.d/80-ipa-add-buildinfo
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-cleanup-dracut/cleanup.d/99-ipa-cleanup-dracut
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-file-injector/environment.d/99-install-file-injector
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-file-injector/install.d/99-enable-ipa-file-injector
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.service.template
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-module-autoload/install.d/80-ipa-module-autoload
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/override-simple-init/environment.d/99-override-simple-init
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/override-simple-init/post-install.d/99-override-simple-init
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/override-simple-init/post-install.d/glean-early-override-template.service
  jenkins/scripts/harbor/harbor_utils.sh
Labels: approved, lgtm, size/XXL

#792 Add bml integration tests jobs to prow
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#788 Fix manifest collection in failed test
  jenkins/scripts/dynamic_worker_workflow/fetch_logs.sh
  jenkins/scripts/files/run_fetch_logs.sh
Labels: approved, lgtm, size/L

#794 Fix merging PR branch in bml tests
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/scripts/bare_metal_lab/default_vars/vars.yaml
  jenkins/scripts/bare_metal_lab/tasks/cleanup-tasks.yaml
  jenkins/scripts/bml_cleanup.sh
  jenkins/scripts/bml_integration_test.sh
Labels: size/M, approved, lgtm

#784 Push CI images to both Xerces and Cleura
  jenkins/image_building/build-image.sh
  jenkins/image_building/upload-ci-image.sh
  jenkins/jobs/image_building.pipeline
Labels: size/M, approved, lgtm

#795 Add image testing to node image building process
  jenkins/image_building/build-image.sh
  jenkins/image_building/verify-node-image.sh
  jenkins/scripts/dynamic_worker_workflow/test_env.sh
Labels: size/M, approved, lgtm

#796 :seedling: Add config for basic-checks container image
  prow/container-images/basic-checks/Dockerfile
  prow/container-images/basic-checks/README.md
Labels: size/S, approved, lgtm

#789 Delete ironic image build pipeline
  jenkins/jobs/ironic_image_build_test.pipeline
  jenkins/scripts/ironic_build_test.sh
  jenkins/scripts/ironic_image_build_test_delete.sh
  jenkins/scripts/start_ironic_image_build_test.sh
Labels: approved, lgtm, size/L
