Repository metal3-io/project-infra, pull requests merged in 2024-03, with the labels that each got.

#644 Disable health check for CI VMs
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#646 Run dev-env's 01 scripts in all integration tests
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#647 Update prow integration tests pipeline
  jenkins/jobs/prow_integration_tests.pipeline
Labels: size/XS

#649 Add ci_git_credential_id to basic e2e test pipeline
  jenkins/jobs/prow_integration_tests.pipeline
Labels: size/XS

#650 Fix UPDATED_REPO in the pipeline for e2e test trigger from prow
  jenkins/jobs/prow_integration_tests.pipeline
Labels: size/S, approved, lgtm

#648 BMO e2e merge before build
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/XS, approved, lgtm

#652 BMO e2e: Specify merge remote
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/XS, approved, lgtm

#653 BMO e2e: Set user name and email for git
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/XS, approved, lgtm

#654 BMO e2e: Fix syntax
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/XS, approved, lgtm

#655 Prow: Run autobumper monthly
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#656 🌱 Run prow triggerable basic e2e on project-infra and fix branch issue
  jenkins/jobs/prow_integration_tests.pipeline
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#657 Fix ci image building pipeline name
  jenkins/jobs/ci_image_building.pipeline
Labels: size/XS, approved, lgtm

#660 fix BMO required tests to match GH settings
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#662 Adds number on install script's name
  jenkins/image_building/dib_elements/centos-ci/install.d/55-install
  jenkins/image_building/dib_elements/ubuntu-ci/install.d/55-install
Labels: size/XS, approved, lgtm

#663 Make basic e2e test triggerable from different repos and os
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#645 Check CI VM cloud-init exit code instead of output
  jenkins/scripts/integration_test.sh
  jenkins/scripts/utils.sh
Labels: size/S, approved, lgtm

#665 Fix prow trigger naming for basic e2e test
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#666 Revert "Check CI VM cloud-init exit code instead of output"
  jenkins/scripts/integration_test.sh
  jenkins/scripts/utils.sh
Labels: size/S, approved, lgtm

#658 Fetch changes from pr-id when triggering from prow
  jenkins/jobs/prow_integration_tests.pipeline
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#668 fix project-infra url
  jenkins/jobs/prow_integration_tests.pipeline
Labels: size/XS, approved, lgtm

#664 Set jenkins worker for BML job
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/scripts/bml_cleanup.sh
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/fetch_logs.sh
Labels: size/M, approved, lgtm

#659 🌱 clusterctl upgrade test
  .gitignore
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: approved, lgtm, size/L

#671 Minor fix in e2e pipeline script.
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: size/XS, approved, lgtm

#672 Add e2e integration trigger to prow
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#643 :sparkles: Switch integration tests from static workers to dynamic workers
  jenkins/jobs/dev_env_integration_tests.pipeline
  jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
Labels: approved, lgtm, size/L

#673 🌱 removing VM_KEY, not needed anymore
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: size/XS, approved, lgtm

#675 Add feature tests triggers to prow config
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#674 Update feature tests pipeline to trigger them from prow
  jenkins/jobs/parallel_e2e_features_test.pipeline
Labels: size/S, approved, lgtm

#676 Use dhcp provided dns address for metal3ci ubuntu images
  jenkins/image_building/dib_elements/ubuntu-ci/post-install.d/configure
Labels: size/XS, approved, lgtm

#677 Fetch changes from PR id with prow feature tests triggers
  jenkins/scripts/dynamic_worker_workflow/feature_tests.sh
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/XS, approved, lgtm

#680 Initialize prow support for ironic-standalone-operator
  prow/manifests/overlays/metal3/config.yaml
  prow/manifests/overlays/metal3/plugins.yaml
Labels: size/M, approved, lgtm
