Repository metal3-io/project-infra, pull requests merged in 2024-04, with the labels that each got.

#683 Trigger upgrade tests from prow
  jenkins/jobs/capm3-e2e-tests.pipeline
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/XL

#682 Add cluster-autoscaler for prow cluster
  prow/README.md
  prow/capo-cluster/machinedeployment.yaml
  prow/cluster-resources/autoscaler.yaml
  prow/cluster-resources/coredns-pdb.yaml
  prow/cluster-resources/kustomization.yaml
Labels: approved, lgtm, size/L

#684 Prow: Add infra node pool
  prow/capo-cluster/infra-kct.yaml
  prow/capo-cluster/infra-md.yaml
  prow/capo-cluster/kustomization.yaml
  prow/cluster-resources/kustomization.yaml
  prow/cluster-resources/toleration-node-selector-patch.yaml
  prow/infra/kustomization.yaml
  prow/infra/toleration-node-selector-patch.yaml
  prow/manifests/overlays/metal3/kustomization.yaml
  prow/manifests/overlays/metal3/toleration-node-selector-patch.yaml
Labels: approved, lgtm, size/L

#685 Fix upgrade test pipeline and set the trigger branches
  jenkins/jobs/capm3-e2e-tests.pipeline
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#690 Fix refspec with prow pipeline when running on project-infra PRs
  jenkins/jobs/capm3-e2e-tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/jobs/prow_integration_tests.pipeline
Labels: size/S, approved, lgtm

#691 Simplify BMO e2e pipeline matrix
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/M, approved, lgtm

#692 Fix missing refspec var
  jenkins/jobs/capm3-e2e-tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/jobs/prow_integration_tests.pipeline
Labels: size/XS, approved, lgtm

#688 Add PR_ID to upgrade pipeline
  jenkins/jobs/capm3-e2e-tests.pipeline
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#693 Run e2e on ironic-image repo
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#696 update ironic-image required tests to Prow tests
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#698 Make tests triggered with prow required instead of ghprb
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#699 🌱 Increasing timout for clusterctl upgrade tests
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: size/XS, approved, lgtm

#700 Make two tests required on main and only ubuntu on releases
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#695 Trigger integration clean from prow
  jenkins/jobs/integration_tests_clean.pipeline
Labels: size/S, approved, lgtm

#703 remove keep test related variables and configs
  jenkins/README.md
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/jobs/prow_integration_tests.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/dynamic_worker_workflow/feature_tests.sh
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
  jenkins/scripts/integration_clean.sh
  jenkins/scripts/integration_delete.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_clean.sh
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/XL

#701 Make e2e run on other repos from prow
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#697 🌱 Update for CAPM3 and IPAM release-1.7 and BMO 0.6.0
  jenkins/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/XL

#709 Fail on pipe failure for openstack commands
  jenkins/scripts/integration_test.sh
Labels: size/XS, approved, lgtm

#708 🌱 Build ironic always from source
  jenkins/scripts/integration_test.sh
Labels: size/S, approved, lgtm

#710 🐛 Fixes related to release capm3/ipam 1.7 and bmo 0.6.0
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#711 make all prow config k8s yaml indented
  prow/manifests/overlays/metal3/config.yaml
  prow/manifests/overlays/metal3/external-plugins/needs-rebase_deployment.yaml
  prow/manifests/overlays/metal3/labels.yaml
  prow/manifests/overlays/metal3/plugins.yaml
Labels: approved, lgtm, size/XXL

#712 revise required Prow tests
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#717 Remove indentation space from pipeline files
  jenkins/jobs/dev_env_integration_tests.pipeline
  jenkins/jobs/integration_tests_clean.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
Labels: size/M, approved, lgtm

#720 Prow: Update CAPO resources to use v1beta1 API
  prow/capo-cluster/cluster.yaml
  prow/capo-cluster/infra-md.yaml
  prow/capo-cluster/kubeadmcontrolplane.yaml
  prow/capo-cluster/machinedeployment.yaml
  prow/capo-cluster/openstackcluster.yaml
  prow/capo-cluster/openstackmachinetemplates.yaml
Labels: size/M, approved, lgtm

#716 Add libvirt related packages for CI image
  jenkins/image_building/dib_elements/centos-ci/install.d/55-install
  jenkins/image_building/dib_elements/ci-base/package-installs.yaml
  jenkins/image_building/dib_elements/ci-base/pkg-map
  jenkins/image_building/dib_elements/ubuntu-ci/install.d/55-install
Labels: size/S, approved, lgtm

#704 Fix unbound UPDATED_REPO error on dev env tests
  jenkins/jobs/dev_env_integration_tests.pipeline
  jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
Labels: size/S, approved, lgtm
