Repository metal3-io/project-infra, pull requests merged in 2024-07, with the labels that each got.

#797 :seedling: Use basic-checks image instead of docker.io/golang for basic tests in BMO repo
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#804 BML: Use server 5 instead of server 6
  jenkins/scripts/bare_metal_lab/default_vars/vars.yaml
Labels: size/S, approved, lgtm

#803 remove KUBECTL_SHA256 passthru
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/capm3-e2e-tests.pipeline
  jenkins/jobs/image_building.pipeline
  jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh
  jenkins/scripts/files/run_integration_tests.sh
Labels: size/S, approved, lgtm

#806 bump spellcheck to 8.9.0
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#798 cleanup basic-checks image
  prow/container-images/basic-checks/Dockerfile
Labels: size/XS, approved, lgtm

#801 Build qcow2 image instead of raw by default
  jenkins/image_building/build-image.sh
  jenkins/image_building/upload-ci-image.sh
Labels: size/XS, approved, lgtm

#808 Remove old SSH key from the CI image
  jenkins/image_building/authorized_keys
Labels: size/XS, approved, lgtm

#809 fix dynamic fullstack
  jenkins/jobs/dynamic_fullstack_building.pipeline
  jenkins/scripts/dynamic_worker_workflow/fullstack.sh
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-add-buildinfo/install.d/80-ipa-add-buildinfo
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-file-injector/environment.d/99-install-file-injector
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.service.template
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/override-simple-init/environment.d/99-override-simple-init
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/override-simple-init/post-install.d/glean-early-override-template.service
Labels: size/XS, approved, lgtm

#810 add missing bmo serial patch for fullstack test
  jenkins/scripts/dynamic_worker_workflow/bmh-patch-short-serial.yaml
  jenkins/scripts/dynamic_worker_workflow/build_ipa.sh
Labels: size/XS, approved, lgtm

#812 Set disk image builder to latest 3.33.0 version
  jenkins/image_building/build-image.sh
Labels: size/XS, approved, lgtm

#811 Run feature tests independently
  jenkins/jobs/e2e_features_test.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
Labels: approved, lgtm, size/L

#813 :seedling: Set trap to cleanup in build-image.sh
  jenkins/image_building/build-image.sh
Labels: size/S, approved, lgtm

#814 Update PROW config feature tests triggers
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/XL

#815 :seedling: Make sure the git clone destination is empty
  jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
Labels: size/XS, approved, lgtm

#816 :bug: Fix IMAGE_LOCATION in build-image.sh
  jenkins/image_building/build-image.sh
  jenkins/image_building/verify-node-image.sh
Labels: size/S, approved, lgtm

#817 🌱 Remove 1.5 clusterctl tests
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#819 :bug: Increase timeout minutes for node image building pipeline
  jenkins/jobs/image_building.pipeline
Labels: size/XS, approved, lgtm

#820 :seedling: Set trap to run `make clean` after integration test
  jenkins/image_building/verify-node-image.sh
  jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
Labels: size/S, approved, lgtm

#821 Update prow config to test release 1.7 of capm3 with go v1.22
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#822 Test ipam 1.7 release with go 1.22
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#823 Test bmo release 0.6 with golang 1.22
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#825 Test capm3 release 1.6 with golang 1.22
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#829 🌱 Fix Calico CrashLoopBackOff in ubuntu e2e tests
  jenkins/image_building/dib_elements/ubuntu-node/post-install.d/90-pre-pull-images
Labels: size/XS, approved, lgtm
