Repository metal3-io/project-infra, pull requests merged in 2024-01, with the labels that each got.

#605 BMO e2e pipeline matrix
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/M, approved, lgtm

#613 Add release-1.6 branch configurations for CAPM3/IPAM repos
  jenkins/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#615 Make BMO e2e tests required status check
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#614 enable build timestamps
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/bmo_e2e_tests.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/integration_tests_clean.pipeline
  jenkins/jobs/ironic_image_build_test.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
Labels: approved, lgtm, size/L

#611 Run feature tests in dynamic Jenkins workers
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/scripts/dynamic_worker_workflow/feature_tests.sh
  jenkins/scripts/dynamic_worker_workflow/fetch_logs.sh
  jenkins/scripts/dynamic_worker_workflow/integration_test_env.sh
  jenkins/scripts/dynamic_worker_workflow/run_clean.sh
Labels: approved, lgtm, size/XL

#616 remove release-1.3 from prow
  jenkins/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#617 Add BMO upgrade tests pipeline
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/XS, approved, lgtm

#618 Trigger BMO e2e tests through prow
  jenkins/jobs/bmo_e2e_tests.pipeline
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#620 Fix typos in prow config for jenkins-operator
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#621 Make BMO e2e prow job required
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#622 Remove the ghprb variable from BMO e2e pipeline
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/XS, approved, lgtm

#619 switch markdownlint container to markdownlint-cli2
  .markdownlint-cli2.yaml
  hack/markdownlint.sh
  prow/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#623 add markdownlint for dev-tools repo
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#624 add spellchecker prow test for website repo
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#625 add spellcheck and shellcheck for metal3-docs
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#626 Bump golang to v1.21 for CAPM3 prow jobs
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L
