Repository metal3-io/project-infra, pull requests merged in 2024-05, with the labels that each got.

#727 Fix unbound var and specify repo dir in full path
  jenkins/jobs/dev_env_integration_tests.pipeline
  jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
  jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh
  jenkins/scripts/dynamic_worker_workflow/fetch_logs.sh
  jenkins/scripts/dynamic_worker_workflow/run_clean.sh
  jenkins/scripts/dynamic_worker_workflow/test_env.sh
Labels: size/M, approved, lgtm

#723 Improve image building scripts
  jenkins/image_building/build-image.sh
  jenkins/image_building/dib_elements/centos-ci/post-install.d/55-configure
  jenkins/image_building/dib_elements/centos-ci/post-install.d/99-prepull-images
  jenkins/image_building/dib_elements/centos-node/install.d/55-install
  jenkins/image_building/dib_elements/centos-node/pre-install.d/55-setup-repos
  jenkins/jobs/ci_image_building.pipeline
  jenkins/jobs/image_building.pipeline
Labels: approved, lgtm, size/L

#728 Minor fix related to ci_git_url
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: size/XS, approved, lgtm

#729 Fix unsetting unbound vars
  jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh
Labels: size/S, approved, lgtm

#730 Passes RT credentials to image building
  jenkins/image_building/dib_elements/centos-ci/post-install.d/99-prepull-images
  jenkins/jobs/image_building.pipeline
Labels: size/S, approved, lgtm

#731 🌱 Fix dev-env triggers
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#715 add prow test config dumper
  hack/prow_test_dumper.py
Labels: size/M, approved, lgtm

#733 Define KUBERNETES_VERSION and related variables for k8s upgrade tests
  jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh
Labels: size/S, approved, lgtm

#707 BMO: Make CAPM3 e2e tests optional
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#736 remove bmo release-0.3 from project-infra
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#741 Prow: Enable blunderbuss
  prow/manifests/overlays/metal3/plugins.yaml
Labels: size/XS, approved, lgtm

#734 Bump CRIO to v1.30.0
  jenkins/image_building/build-image.sh
Labels: size/XS, approved, lgtm

#742 Fix e2e integration test run from metal3-dev-env repo PR
  jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh
Labels: size/XS, approved, lgtm

#739 Move BMO e2e jobs to run on Xerces workers
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/XS, approved, lgtm

#743 remove e2e from bmo 0.6 branch as required
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#746 Increase BMO e2e timeout
  jenkins/jobs/bmo_e2e_tests.pipeline
Labels: size/XS, approved, lgtm

#747 Adjust timeout for tests
  jenkins/jobs/capm3-e2e-tests.pipeline
  jenkins/jobs/dev_env_integration_tests.pipeline
Labels: size/S, approved, lgtm

#748 Set dev env tests as required for metal3-dev-env repo
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#750 🌱 Move furkatgofurov7 to emeritus approvers
  OWNERS
Labels: size/XS, approved, lgtm

#749 Fix git credentials ID
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/bmo_e2e_tests.pipeline
  jenkins/jobs/capm3-e2e-tests.pipeline
  jenkins/jobs/dev_env_integration_tests.pipeline
  jenkins/jobs/image_building.pipeline
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/integration_tests_clean.pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
  jenkins/jobs/prow_integration_tests.pipeline
Labels: size/M, approved, lgtm

#751 Remove ghprb related variables from feature tests pipeline
  jenkins/jobs/parallel_e2e_features_test.pipeline
Labels: size/M, approved, lgtm

#753 Prow: Increase max prowjob age to 24h
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#752 Prow: Skip job report from jenkins-operator
  prow/manifests/overlays/metal3/external-plugins/jenkins-operator.yaml
Labels: size/XS, approved, lgtm

#754 Prow: Update readme
  prow/README.md
Labels: size/S, approved, lgtm

#756 Prow: Enable triggering of GitHub workflows
  prow/manifests/overlays/metal3/plugins.yaml
Labels: size/XS, approved, lgtm

#757 🐛 Fixing EPHEMERAL_TEST variable
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: size/XS, approved, lgtm

#758 Prow: Add metal3-io org to triggers config
  prow/manifests/overlays/metal3/plugins.yaml
Labels: size/XS, approved, lgtm

#760 skip if only OWNERS_ALIASES is modified
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#761 add OWNERS_ALIASES support
  OWNERS
  OWNERS_ALIASES
Labels: size/S, approved, lgtm

#766 Add new key to authorized_keys in the DiB build
  jenkins/image_building/authorized_keys
  jenkins/image_building/build-image.sh
Labels: size/XS, approved, lgtm

#764 add cherrypicker to sles-ironic-python-agent-builder
  prow/manifests/overlays/metal3/plugins.yaml
Labels: size/XS, approved, lgtm

#759 Remove ghprb vars from bml pipeline
  jenkins/jobs/bml_integration_tests.pipeline
Labels: size/M, approved, lgtm

#769 Remove unused scripts and variables from project infra
  jenkins/jobs/integration_tests.pipeline
  jenkins/jobs/prow_integration_tests.pipeline
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_clean.sh
  jenkins/scripts/files/run_fetch_logs.sh
  jenkins/scripts/integration_test.sh
  jenkins/scripts/integration_test_clean.sh
  jenkins/scripts/utils.sh
Labels: approved, lgtm, size/XL

#770 Prow: Enable reporting again in jenkins-operator
  prow/manifests/overlays/metal3/external-plugins/jenkins-operator.yaml
Labels: size/XS, approved, lgtm

#768 Build diskimage builder from upstream commit until next release
  jenkins/image_building/build-image.sh
Labels: size/S, approved, lgtm

#775 shellcheck only files
  hack/shellcheck.sh
Labels: size/XS, approved, lgtm

#772 Bump golang to v1.22 for CAPM3, BMO and IPAM prow jobs
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#774 Cleanup old integration tests scripts
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/fetch_logs.sh
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/L
