Repository metal3-io/project-infra, pull requests merged in 2024-12, with the labels that each got.

#924 Prow: Use flavors with local disk
  prow/capo-cluster/infra-md.yaml
  prow/capo-cluster/kubeadmcontrolplane.yaml
  prow/capo-cluster/machinedeployment.yaml
  prow/capo-cluster/openstackmachinetemplates.yaml
Labels: size/M, approved, lgtm

#927 :seedling: Add custom ref input to container build workflow
  .github/workflows/container-image-build.yml
Labels: size/M, approved, lgtm

#925 remove ironic-client from Prow
  prow/config/config.yaml
  prow/config/jobs/metal3-io/ironic-client.yaml
  prow/config/plugins.yaml
Labels: size/M, approved, lgtm

#929 :seedling: Bump k8s to 1.32.0, crictl to 1.32.0 and crio to 1.31.3
  jenkins/image_building/build-image.sh
Labels: size/XS, approved, lgtm

#932 remove IPAM 1.6 from Prow
  prow/config/jobs/metal3-io/ip-address-manager-release-1.6.yaml
Labels: approved, lgtm, size/L

#931 add IPAM 1.9 release to Prow
  prow/config/jobs/metal3-io/ip-address-manager-release-1.9.yaml
Labels: approved, lgtm, size/L

#935 remove untested branches (1.6 series) from Prow
  jenkins/README.md
  prow/config/jobs/metal3-io/baremetal-operator-release-0.5.yaml
  prow/config/jobs/metal3-io/cluster-api-provier-metal3-release-1.6.yaml
  prow/config/jobs/metal3-io/ironic-image-release-24.0.yaml
  prow/config/jobs/metal3-io/ironic-ipa-downloader.yaml
  prow/config/jobs/metal3-io/mariadb-image.yaml
  prow/config/jobs/metal3-io/metal3-dev-env.yaml
  prow/config/jobs/metal3-io/project-infra.yaml
  prow/config/plugins.yaml
Labels: approved, lgtm, size/XL

#933 add BMO release-0.9 to Prow
  prow/config/jobs/metal3-io/baremetal-operator-release-0.9.yaml
Labels: approved, lgtm, size/L

#938 add mquhuy as reviewer
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#936 add release-1.9 triggers to other repos
  jenkins/README.md
  prow/config/jobs/metal3-io/ironic-ipa-downloader.yaml
  prow/config/jobs/metal3-io/mariadb-image.yaml
  prow/config/jobs/metal3-io/metal3-dev-env.yaml
  prow/config/plugins.yaml
Labels: size/M, approved, lgtm

#939 remove old 1.8 tests from required for dev-env
  prow/config/jobs/metal3-io/metal3-dev-env.yaml
Labels: size/XS, approved, lgtm

#940 run ironic-image 27.0 tests versus release-1.9
  prow/config/jobs/metal3-io/ironic-image-release-27.0.yaml
Labels: size/XS, approved, lgtm

#941 :bug: fix incorrect PR title handling
  .github/workflows/pr-verifier.yaml
Labels: size/S, approved, lgtm
