Repository metal3-io/project-infra, pull requests merged in 2024-02, with the labels that each got.

#630 Update required contexts for BMO
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#631 Prow: Bump ingress-nginx to v1.9.6
  prow/infra/kustomization.yaml
Labels: size/XS, approved, lgtm

#634 Add config for ironic-image release-24.0
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#632 ✨ Added generic-autobumper to update all prow images
  prow/manifests/overlays/metal3/config.yaml
  prow/manifests/overlays/metal3/generic-autobumper-config.yaml
  prow/manifests/overlays/metal3/kustomization.yaml
Labels: approved, lgtm, size/L

#627 Bump golang to v1.21 for BMO prow jobs
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#635 Bump golang to v1.21 for IPAM prow jobs
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#638 🐛Typo fix
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#640 :seedling: Group images by prefix to make PR title more readable
  prow/manifests/overlays/metal3/generic-autobumper-config.yaml
Labels: approved, lgtm, size/L

#641 Prow: Restore patches that were mistakenly removed
  prow/manifests/overlays/metal3/kustomization.yaml
Labels: size/S, approved, lgtm

#636 Add image building with diskimage-builder
  jenkins/image_building/README.md
  jenkins/image_building/build-ci-image.sh
  jenkins/image_building/dib_elements/centos-ci/README.md
  jenkins/image_building/dib_elements/centos-ci/element-deps
  jenkins/image_building/dib_elements/centos-ci/install.d/install
  jenkins/image_building/dib_elements/centos-ci/post-install.d/configure
  jenkins/image_building/dib_elements/ci-base/README.md
  jenkins/image_building/dib_elements/ci-base/element-deps
  jenkins/image_building/dib_elements/ci-base/package-installs.yaml
  jenkins/image_building/dib_elements/ci-base/pkg-map
  jenkins/image_building/dib_elements/ubuntu-ci/README.md
  jenkins/image_building/dib_elements/ubuntu-ci/element-deps
  jenkins/image_building/dib_elements/ubuntu-ci/install.d/install
  jenkins/image_building/dib_elements/ubuntu-ci/post-install.d/configure
  jenkins/image_building/id_ed25519_metal3ci.pub
  jenkins/jobs/openstack_ci_image_building.pipeline
Labels: approved, lgtm, size/XL

#642 Add new pipeline to test triggering basic e2e from prow
  jenkins/jobs/prow_integration_tests.pipeline
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L
