Repository metal3-io/project-infra, pull requests merged in 2024-09, with the labels that each got.

#851 remove BMO 0.4 from Prow and add missing 0.8 tests
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#853 :seedling: Remove tests related to release-1.5
  jenkins/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#852 Update outdated cleanup jobs
  jenkins/jobs/clean_resources.pipeline
  jenkins/scripts/clean_resources.sh
  jenkins/scripts/integration_clean.sh
Labels: approved, lgtm, size/L

#854 Fix typo
  jenkins/scripts/clean_resources.sh
Labels: size/XS, approved, lgtm

#857 🌱 Bump ingress-nginx in prow to v1.10.4
  prow/README.md
  prow/infra/kustomization.yaml
  prow/manifests/overlays/metal3/kustomization.yaml
Labels: size/S, approved, lgtm

#858 Allow uploading the latest image under a common name
  jenkins/image_building/upload-ci-image.sh
Labels: size/S, approved, lgtm

#861 :seedling: Add pr-verifier-workflow
  .github/workflows/pr-verifier.yaml
Labels: size/M, approved, lgtm

#862 add dependabot config for github actions bumps
  .github/dependabot.yml
Labels: size/S, approved, lgtm

#865 Pin basic-checks image, and add workflow for building it
  .github/workflows/build-images-action.yml
  .github/workflows/container-image-build.yml
  prow/container-images/basic-checks/Dockerfile
  prow/container-images/basic-checks/README.md
Labels: size/M, approved, lgtm

#866 add missing dockerfile-directory for basic-checks
  .github/workflows/build-images-action.yml
Labels: size/XS, approved, lgtm

#867 fix image-tag reference
  .github/workflows/container-image-build.yml
Labels: size/XS, approved, lgtm

#868 add reusable container build as trigger file path
  .github/workflows/build-images-action.yml
Labels: size/XS, approved, lgtm
