Repository metal3-io/project-infra, pull requests merged in 2024-08, with the labels that each got.

#830 Test bmo release 0.5 with golang 1.22
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#828 Test ipam release 1.6 with golang 1.22
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#833 :seedling: Add container image build wf template
  .github/workflows/container-image-build.yml
Labels: size/M, approved, lgtm

#834 :seedling: Changing default permissions in container-image-build-wf to read
  .github/workflows/container-image-build.yml
Labels: size/XS, approved, lgtm

#836 Uplift kubernetes version to v1.31.0 for image building
  jenkins/image_building/build-image.sh
Labels: size/XS, approved, lgtm

#835 Remove EoL ironic-image 23.1 from config
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#827 :seedling: Change image-building pipeline to a matrix
  jenkins/image_building/build-image.sh
  jenkins/image_building/upload-node-image.sh
  jenkins/image_building/verify-node-image.sh
  jenkins/jobs/image_building.pipeline
  jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
Labels: approved, lgtm, size/L

#839 Fix agent label with actual flavor
  jenkins/jobs/capm3-e2e-tests.pipeline
  jenkins/jobs/dev_env_integration_tests.pipeline
Labels: size/XS, approved, lgtm

#840 :seedling: Add python3-dev package to build-image.sh
  jenkins/image_building/build-image.sh
Labels: size/S, approved, lgtm

#842 :seedling: Adapt ci-image wf to image-build pipeline
  jenkins/image_building/build-image.sh
  jenkins/image_building/upload-ci-image.sh
  jenkins/jobs/image_building.pipeline
Labels: size/M, approved, lgtm

#843 :seedling: Regroup prow config tests by names
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#832 :seedling: Add release-1.8 configurations
  jenkins/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#846 :seedling: Change BMO release-0.7 to release-0.8
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#844 Move image building jobs to private cloud
  jenkins/jobs/image_building.pipeline
Labels: size/XS, approved, lgtm

#845 Move k8s upgrade and e2e other feature tests to private cloud
  jenkins/jobs/capm3-e2e-tests.pipeline
  jenkins/jobs/e2e_features_test.pipeline
Labels: size/XS, approved, lgtm

#847 Do not upload images to fra region
  jenkins/image_building/upload-ci-image.sh
Labels: size/XS, approved, lgtm

#848 Update config for ironic-image release-26.0
  prow/manifests/overlays/metal3/config.yaml
Labels: size/S, approved, lgtm

#849 fix required tests in prow config for ipam and ironic-image
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm
