Repository metal3-io/project-infra, pull requests merged in 2024-11, with the labels that each got.

#888 🌱 uplift k8s to v1.31.2
  jenkins/image_building/build-image.sh
Labels: size/XS, approved, lgtm

#892 Catch curl upload error when upload fails
  jenkins/image_building/upload-node-image.sh
  jenkins/scripts/artifactory/utils.sh
Labels: size/S, approved, lgtm

#884 improve robustness of the initrd sdk
  .gitignore
  jenkins/image_building/initrd_sdk/test_unlock_config
  jenkins/image_building/initrd_sdk/tpm2-unseal-key.sh
  jenkins/image_building/initrd_sdk/unlock-mount-luks.sh
  jenkins/image_building/initrd_sdk/unseal-and-open-luks.service
  jenkins/image_building/initrd_sdk/verify-realroot.sh
Labels: approved, lgtm, size/XL

#893 Prow: Define jobs per release branch
  prow/README.md
  prow/config/jobs/metal3-io/baremetal-operator-release-0.5.yaml
  prow/config/jobs/metal3-io/baremetal-operator-release-0.6.yaml
  prow/config/jobs/metal3-io/baremetal-operator-release-0.8.yaml
  prow/config/jobs/metal3-io/baremetal-operator.yaml
  prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml
  prow/config/jobs/metal3-io/cluster-api-provier-metal3-release-1.6.yaml
  prow/config/jobs/metal3-io/cluster-api-provier-metal3-release-1.7.yaml
  prow/config/jobs/metal3-io/cluster-api-provier-metal3-release-1.8.yaml
  prow/config/jobs/metal3-io/ip-address-manager-release-1.6.yaml
  prow/config/jobs/metal3-io/ip-address-manager-release-1.7.yaml
  prow/config/jobs/metal3-io/ip-address-manager-release-1.8.yaml
  prow/config/jobs/metal3-io/ip-address-manager.yaml
  prow/config/jobs/metal3-io/ironic-image-release-24.0.yaml
  prow/config/jobs/metal3-io/ironic-image-release-24.1.yaml
  prow/config/jobs/metal3-io/ironic-image-release-25.0.yaml
  prow/config/jobs/metal3-io/ironic-image-release-26.0.yaml
  prow/config/jobs/metal3-io/ironic-image.yaml
Labels: approved, lgtm, size/XXL

#895 Prow: Configure milestone applier plugin
  prow/config/plugins.yaml
Labels: size/S, approved, lgtm

#894 Update prow_test_dumper.py to handle job-config
  hack/prow_test_dumper.py
Labels: size/S, approved, lgtm

#897 Prow: Fix milestone applier config
  prow/config/plugins.yaml
Labels: size/M, approved, lgtm

#898 Fix CI image upload issue
  jenkins/image_building/upload-ci-image.sh
Labels: size/XS, approved, lgtm

#899 Update KCT and KCP with new cloud-init structure
  prow/capo-cluster/infra-kct.yaml
  prow/capo-cluster/kubeadmconfigtemplate.yaml
  prow/capo-cluster/kubeadmcontrolplane.yaml
Labels: size/S, approved, lgtm

#900 Prow: Upgrade Kubernetes and CAPI/CAPO
  prow/README.md
  prow/capo-cluster/infra-md.yaml
  prow/capo-cluster/kubeadmcontrolplane.yaml
  prow/capo-cluster/machinedeployment.yaml
  prow/capo-cluster/openstackmachinetemplates.yaml
Labels: size/M, approved, lgtm

#901 Prow: Bump calico, autoscaler and cloud-provider
  prow/capo-cluster/machinedeployment.yaml
  prow/cluster-resources/autoscaler.yaml
  prow/cluster-resources/kustomization.yaml
Labels: size/S, approved, lgtm

#903 Prow: Temporary autoscaler RBAC workaround
  prow/cluster-resources/autoscaler.yaml
Labels: size/S, approved, lgtm

#902 update basic-checks image to Go 1.23
  .github/workflows/build-images-action.yml
  prow/container-images/basic-checks/Dockerfile
Labels: size/XS, approved, lgtm

#905 🌱 Fixing agent creation timeout issue
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: size/XS, approved, lgtm

#904 update basic-checks baseimage when building it
  .github/workflows/build-images-action.yml
  prow/container-images/basic-checks/Dockerfile
Labels: size/XS, approved, lgtm

#909 bump prow tests to Go 1.23
  prow/config/jobs/metal3-io/baremetal-operator-release-0.8.yaml
  prow/config/jobs/metal3-io/baremetal-operator.yaml
  prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml
  prow/config/jobs/metal3-io/cluster-api-provier-metal3-release-1.8.yaml
  prow/config/jobs/metal3-io/ip-address-manager-release-1.8.yaml
  prow/config/jobs/metal3-io/ip-address-manager.yaml
  prow/config/jobs/metal3-io/ironic-standalone-operator.yaml
Labels: size/M, approved, lgtm

#908 Prow: Switch to staging registry
  prow/Makefile
  prow/config/config.yaml
  prow/config/generic-autobumper-config.yaml
  prow/config/jobs/metal3-io/project-infra.yaml
  prow/config/jobs/periodics.yaml
  prow/manifests/base/crier.yaml
  prow/manifests/base/deck.yaml
  prow/manifests/base/ghproxy.yaml
  prow/manifests/base/hook.yaml
  prow/manifests/base/horologium.yaml
  prow/manifests/base/prow-controller-manager.yaml
  prow/manifests/base/sinker.yaml
  prow/manifests/base/statusreconciler.yaml
  prow/manifests/base/tide.yaml
  prow/manifests/overlays/metal3/external-plugins/cherrypicker_deployment.yaml
  prow/manifests/overlays/metal3/external-plugins/jenkins-operator.yaml
  prow/manifests/overlays/metal3/external-plugins/labels_cronjob.yaml
  prow/manifests/overlays/metal3/external-plugins/needs-rebase_deployment.yaml
Labels: size/M, approved, lgtm

#910 Prow: Add Makefile to autobumper
  prow/config/generic-autobumper-config.yaml
Labels: size/XS, approved, lgtm

#912 Prow: Use GCR for commenter and label_sync images
  prow/config/generic-autobumper-config.yaml
  prow/config/jobs/periodics.yaml
  prow/manifests/overlays/metal3/external-plugins/labels_cronjob.yaml
Labels: size/S, approved, lgtm

#913 Move rest of the test to private cloud
  jenkins/jobs/capm3-e2e-tests.pipeline
  jenkins/jobs/dynamic_fullstack_building.pipeline
  jenkins/jobs/e2e_features_test.pipeline
Labels: size/S, approved, lgtm

#916 Prow: Update docs
  prow/README.md
Labels: size/XS, approved, lgtm

#917 Prow: Use CAPI Operator
  .cspell-config.json
  prow/README.md
  prow/capi/bootstrap.yaml
  prow/capi/control-plane.yaml
  prow/capi/core.yaml
  prow/capi/infrastructure.yaml
  prow/capi/kustomization.yaml
Labels: size/M, approved, lgtm

#915 Improve Prow test dumper script to crosscheck settings with GitHub branchprotections
  hack/prow_test_dumper.py
Labels: size/M, approved, lgtm

#919 Add configuration for ironic-image release-27.0
  prow/config/jobs/metal3-io/ironic-image-release-27.0.yaml
Labels: size/M, approved, lgtm

#921 add blunderbuss to Nordix repos
  prow/config/plugins.yaml
Labels: size/XS, approved, lgtm
