Repository metal3-io/project-infra, pull requests merged in 2024-10, with the labels that each got.

#856 Add support for lvm, cryptsetup, tpm2_tools
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-luks-tpm-support/install.d/99-install-luks-tpm
  jenkins/scripts/dynamic_worker_workflow/ipa_builder_elements/ipa-lvm-support/install.d/99-install-lvm2
Labels: size/S, approved, lgtm

#875 bump markdownlint-cli2 to v0.12.0
  hack/markdownlint.sh
  prow/manifests/overlays/metal3/config.yaml
Labels: size/M, approved, lgtm

#874 bump cspell to v8.13.3
  prow/manifests/overlays/metal3/config.yaml
Labels: size/XS, approved, lgtm

#873 add initial commit of the initrd sdk
  jenkins/image_building/initrd_sdk/README.md
  jenkins/image_building/initrd_sdk/unlock-mount-luks.sh
Labels: approved, lgtm, size/L

#877 extending the initrd_sdk
  jenkins/image_building/initrd_sdk/README.md
  jenkins/image_building/initrd_sdk/unseal-and-open-luks.service
  jenkins/image_building/initrd_sdk/verify-realroot.sh
Labels: size/M, approved, lgtm

#876 bump golang to 1.22.8 in basic-checks image
  prow/container-images/basic-checks/Dockerfile
Labels: size/XS, approved, lgtm

#878 fix typo in initrd_sdk
  jenkins/image_building/initrd_sdk/README.md
Labels: size/XS, approved, lgtm

#880 improve initrd verification logic
  jenkins/image_building/initrd_sdk/unlock-mount-luks.sh
  jenkins/image_building/initrd_sdk/verify-realroot.sh
Labels: size/S, approved, lgtm

#883 add missing DCO file to repo root
  DCO
Labels: size/M, approved, lgtm

#882 add spellcheck basic test and fix spellcheck issues
  .cspell-config.json
  hack/spellcheck.sh
  jenkins/README.md
  jenkins/image_building/dib_elements/ubuntu-node/README.md
  jenkins/image_building/initrd_sdk/README.md
  prow/README.md
  prow/manifests/overlays/metal3/config.yaml
Labels: approved, lgtm, size/L

#886 🌱 Increasing timeout of ephemeral tests
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: size/XS, approved, lgtm
