Repository metal3-io/project-infra, pull requests merged in 2025-03, with the labels that each got.

#967 Prow: Add tolerations and nodeSelectors for CAPI related components and bump versions
  prow/README.md
  prow/capi/bootstrap.yaml
  prow/capi/control-plane.yaml
  prow/capi/core.yaml
  prow/capi/infrastructure.yaml
  prow/capi/kustomization.yaml
  prow/capi/toleration-node-selector-patch.yaml
Labels: approved, lgtm, size/L

#968 Prow: Upgrade kubernetes, ingress, calico and more
  prow/capo-cluster/infra-md.yaml
  prow/capo-cluster/kubeadmcontrolplane.yaml
  prow/capo-cluster/machinedeployment.yaml
  prow/capo-cluster/openstackcluster.yaml
  prow/capo-cluster/openstackmachinetemplates.yaml
  prow/cluster-resources/autoscaler.yaml
  prow/cluster-resources/kustomization.yaml
  prow/infra/add-args.yaml
  prow/infra/configmap-patch.yaml
  prow/infra/kustomization.yaml
Labels: approved, lgtm, size/L

#969 bump basic-checks image to golang 1.23.7
  prow/container-images/basic-checks/Dockerfile
Labels: size/XS, approved, lgtm

#965 move provisioning cluster to jenkins agent in bml
  jenkins/scripts/bare_metal_lab/tasks/deploy-tasks.yaml
  jenkins/scripts/bml_cleanup.sh
  jenkins/scripts/bml_integration_test.sh
  jenkins/scripts/files/run_clean.sh
  jenkins/scripts/files/run_integration_tests.sh
Labels: approved, lgtm, size/L

#971 prow-test-dumper: handle completely missing branch protection case
  hack/prow_test_dumper.py
Labels: size/XS, approved, lgtm

#973 Move @mquhuy to emeritus reviewers
  OWNERS
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#974 Prow: Bump ingress-nginx
  prow/infra/kustomization.yaml
Labels: size/XS, approved, lgtm

#970 :seedling: Add pull bmo e2e optional to prow
  jenkins/jobs/bmo_e2e_optional_tests.pipeline
  prow/config/jobs/metal3-io/baremetal-operator-release-0.8.yaml
  prow/config/jobs/metal3-io/baremetal-operator-release-0.9.yaml
  prow/config/jobs/metal3-io/baremetal-operator.yaml
Labels: approved, lgtm, size/L

#975 Add input to pass build args instead of env
  .github/workflows/container-image-build.yml
Labels: size/XS, approved, lgtm

#976 Add configuration for ironic-image release-29.0
  prow/config/jobs/metal3-io/ironic-image-release-29.0.yaml
  prow/config/plugins.yaml
Labels: size/M, approved, lgtm
