Repository metal3-io/project-infra, pull requests merged in 2025-08, with the labels that each got.

#1057 Install python related packages to run ansible script on node images
  jenkins/image_building/dib_elements/centos-node/install.d/55-install
  jenkins/image_building/dib_elements/centos-node/package-installs.yaml
  jenkins/image_building/dib_elements/ubuntu-node/package-installs.yaml
Labels: size/XS, approved, lgtm

#1044 Add support for Ubuntu 24.04 node images
  jenkins/image_building/build-image.sh
  jenkins/image_building/dib_elements/ubuntu-node/install.d/55-install
Labels: size/S, approved, lgtm

#1064 Add configuration for ironic-image release-31.0
  prow/config/jobs/metal3-io/ironic-image-release-31.0.yaml
  prow/config/plugins.yaml
Labels: size/M, approved, lgtm

#1065 Configure CI for IrSO release-0.5 branch
  prow/config/jobs/metal3-io/ironic-standalone-operator-release-0.5.yaml
  prow/config/plugins.yaml
Labels: size/M, approved, lgtm

#1067 Add prow keywords for k8s pre-release testing
  prow/config/jobs/metal3-io/baremetal-operator.yaml
  prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml
  prow/config/jobs/metal3-io/ip-address-manager.yaml
  prow/config/jobs/metal3-io/metal3-dev-env.yaml
  prow/config/jobs/metal3-io/project-infra.yaml
Labels: size/M, approved, lgtm

#1074 Automatically fetch latest pre-release k8s version
  jenkins/image_building/build-image.sh
  jenkins/jobs/pre_release_tests.pipeline
Labels: size/S, approved, lgtm

#1075 Unify Kubernetes installation scripts in image building
  jenkins/image_building/dib_elements/centos-node/install.d/55-install
  jenkins/image_building/dib_elements/centos-node/pre-install.d/55-setup-repos
  jenkins/image_building/dib_elements/ubuntu-node/install.d/55-install
  jenkins/image_building/dib_elements/ubuntu-node/pre-install.d/55-setup-repos
Labels: approved, lgtm, size/L

#1077 🌱 Bump k8s to 1.34 for image building
  jenkins/image_building/build-image.sh
Labels: size/XS, approved, lgtm
