Repository metal3-io/project-infra, pull requests merged in 2025-06, with the labels that each got.

#1034 add IRSO 0.4 prow jobs
  prow/config/jobs/metal3-io/ironic-standalone-operator-main.yaml
  prow/config/jobs/metal3-io/ironic-standalone-operator-release-0.4.yaml
Labels: size/M, approved, lgtm

#1041 Add CAPI md tests' setup and Prow keywords
  jenkins/jobs/capm3-e2e-tests.pipeline
  prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml
  prow/config/jobs/metal3-io/metal3-dev-env.yaml
  prow/config/jobs/metal3-io/project-infra.yaml
Labels: size/M, approved, lgtm

#1040 Add Prow keywords for conformance tests
  prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml
  prow/config/jobs/metal3-io/metal3-dev-env.yaml
  prow/config/jobs/metal3-io/project-infra.yaml
Labels: size/S, approved, lgtm

#1035 update IRSO milestones
  prow/config/plugins.yaml
Labels: size/XS, approved, lgtm

#1045 Prow: Bump kubernetes, calico and ingress-nginx
  prow/README.md
  prow/capo-cluster/infra-md.yaml
  prow/capo-cluster/kubeadmcontrolplane.yaml
  prow/capo-cluster/machinedeployment.yaml
  prow/capo-cluster/openstackmachinetemplates.yaml
  prow/cluster-resources/kustomization.yaml
  prow/infra/kustomization.yaml
Labels: size/M, approved, lgtm
