Repository metal3-io/project-infra, pull requests merged in 2025-05, with the labels that each got.

#1003 :seedling: Remove release-1.7
  jenkins/README.md
  prow/config/jobs/metal3-io/baremetal-operator-release-0.6.yaml
  prow/config/jobs/metal3-io/cluster-api-provider-metal3-release-1.7.yaml
  prow/config/jobs/metal3-io/ip-address-manager-release-1.7.yaml
  prow/config/jobs/metal3-io/ironic-image-release-24.1.yaml
  prow/config/jobs/metal3-io/ironic-image-release-25.0.yaml
  prow/config/jobs/metal3-io/ironic-image-release-28.0.yaml
  prow/config/jobs/metal3-io/ironic-image-release-29.0.yaml
  prow/config/jobs/metal3-io/ironic-ipa-downloader.yaml
  prow/config/jobs/metal3-io/mariadb-image.yaml
  prow/config/jobs/metal3-io/metal3-dev-env.yaml
  prow/config/jobs/metal3-io/project-infra.yaml
  prow/config/plugins.yaml
Labels: approved, lgtm, size/XL

#1008 bump basic-checks image to 1.23.8
  prow/container-images/basic-checks/Dockerfile
Labels: size/XS, approved, lgtm

#1002 :seedling: Add other release-1.10 triggers to Prow
  jenkins/README.md
  prow/config/jobs/metal3-io/ironic-image-release-28.0.yaml
  prow/config/jobs/metal3-io/ironic-ipa-downloader.yaml
  prow/config/jobs/metal3-io/mariadb-image.yaml
  prow/config/jobs/metal3-io/metal3-dev-env.yaml
  prow/config/plugins.yaml
Labels: size/M, approved, lgtm

#1009 remove centos e2e from required in 1.10 branch
  prow/config/jobs/metal3-io/ip-address-manager-release-1.10.yaml
Labels: size/XS, approved, lgtm

#1007 Fix log fetching and lingering dnsmasq processes in bml
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/scripts/bare_metal_lab/tasks/cleanup-tasks.yaml
  jenkins/scripts/fetch_logs.sh
Labels: size/M, approved, lgtm

#1010 🌱 Changing mandatory tests for metal3-dev-env and adding 1.9,1.10 for project-infra
  prow/config/jobs/metal3-io/metal3-dev-env.yaml
  prow/config/jobs/metal3-io/project-infra.yaml
Labels: approved, lgtm, size/L

#1011 Fix CI image upload
  jenkins/jobs/image_building.pipeline
Labels: size/XS, approved, lgtm

#966 :seedling: Add broken link check: pr and scheduled
  .github/workflows/pr-link-check.yml
  .github/workflows/scheduled-link-check.yml
  .lycheeignore
  jenkins/README.md
  jenkins/scripts/bare_metal_lab/README.md
  prow/README.md
Labels: approved, lgtm, size/L

#1014 :seedling: Fix how Github token is used in link checks workflow
  .github/workflows/pr-link-check.yml
  .github/workflows/scheduled-link-check.yml
Labels: size/XS, approved, lgtm

#1015 :seedling: Set upstream to PR link check
  .github/workflows/pr-link-check.yml
Labels: size/S, approved, lgtm

#1016 :seedling: Fix input in PR-link-check
  .github/workflows/pr-link-check.yml
Labels: size/XS, approved, lgtm

#1012 Fix ansible task error caused by lingering dnsmasq ansible task
  jenkins/scripts/bare_metal_lab/tasks/cleanup-tasks.yaml
  jenkins/scripts/bare_metal_lab/tasks/deploy-tasks.yaml
Labels: size/S, approved, lgtm

#1013 Prow: Bump CAPI components
  prow/capi/bootstrap.yaml
  prow/capi/control-plane.yaml
  prow/capi/core.yaml
  prow/capi/infrastructure.yaml
  prow/capi/kustomization.yaml
Labels: size/S, approved, lgtm

#1017 Tweak PR link check args
  .github/workflows/pr-link-check.yml
Labels: size/XS, approved, lgtm

#1021 fix container tags for main
  .github/workflows/container-image-build.yml
Labels: size/XS, approved, lgtm

#1020 bump basic-checks image to golang:1.24.3
  .github/workflows/build-images-action.yml
  prow/container-images/basic-checks/Dockerfile
Labels: size/XS, approved, lgtm

#1023 Bump CAPM3 release branch prow jobs to use go v1.24
  prow/config/jobs/metal3-io/cluster-api-provider-metal3-release-1.10.yaml
  prow/config/jobs/metal3-io/cluster-api-provider-metal3-release-1.9.yaml
Labels: size/S, approved, lgtm

#1025 Bump BMO prow jobs to use go v1.24
  prow/config/jobs/metal3-io/baremetal-operator-release-0.10.yaml
  prow/config/jobs/metal3-io/baremetal-operator-release-0.9.yaml
  prow/config/jobs/metal3-io/baremetal-operator.yaml
Labels: size/S, approved, lgtm

#1024 Bump IPAM prow jobs to use go v1.24
  prow/config/jobs/metal3-io/ip-address-manager-release-1.10.yaml
  prow/config/jobs/metal3-io/ip-address-manager-release-1.9.yaml
  prow/config/jobs/metal3-io/ip-address-manager.yaml
Labels: size/S, approved, lgtm

#1027 Revert "Prow: Require manually triggered jobs"
  prow/config/config.yaml
Labels: size/XS, approved, lgtm
