Repository metal3-io/project-infra, pull requests merged in 2025-01, with the labels that each got.

#870 fix IPA git commit/branch refference
  jenkins/scripts/dynamic_worker_workflow/build_ipa.sh
Labels: size/XS, approved, lgtm

#942 :seedling: Set scalability test timeout to 6h
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: size/XS, approved, lgtm

#948 bump kubeconform/manifestlint to v0.6.7
  prow/config/jobs/metal3-io/baremetal-operator.yaml
  prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml
  prow/config/jobs/metal3-io/ip-address-manager.yaml
  prow/config/jobs/metal3-io/ironic-standalone-operator.yaml
Labels: size/S, approved, lgtm

#946 add runmariadb script as a shellcheck trigger for mariadb-image
  prow/config/jobs/metal3-io/mariadb-image.yaml
Labels: size/XS, approved, lgtm

#949 :seedling: Merge e2e_features_test to capm3-e2e-tests pipeline
  jenkins/jobs/capm3-e2e-tests.pipeline
Labels: size/S, approved, lgtm

#887 convert fullstack jobs to be prow compatible
  jenkins/jobs/dynamic_fullstack_building.pipeline
  jenkins/scripts/dynamic_worker_workflow/fullstack.sh
  prow/config/jobs/metal3-io/project-infra.yaml
Labels: size/M, approved, lgtm

#953 :seedling: Add scalability test prow triggers
  prow/config/jobs/metal3-io/cluster-api-provider-metal3-release-1.9.yaml
  prow/config/jobs/metal3-io/cluster-api-provider-metal3.yaml
Labels: size/S, approved, lgtm

#950 :seedling: Add support for IRSO in e2e pipeline
  jenkins/jobs/dev_env_integration_tests.pipeline
  jenkins/scripts/dynamic_worker_workflow/dev_env_integration_tests.sh
  prow/config/jobs/metal3-io/ironic-standalone-operator.yaml
Labels: size/M, approved, lgtm

#957 Add vars to image building pipeline
  jenkins/jobs/image_building.pipeline
Labels: size/S, approved, lgtm

#958 Remove uploading ci images to cleura
  jenkins/image_building/upload-ci-image.sh
  jenkins/jobs/clean_resources.pipeline
  jenkins/jobs/image_building.pipeline
  jenkins/scripts/clean_resources.sh
Labels: size/M, approved, lgtm
