Repository metal3-io/project-infra, pull requests merged in 2025-04, with the labels that each got.

#980 Prow: Disable legacy cache option
  prow/manifests/base/ghproxy.yaml
Labels: size/XS, approved, lgtm

#981 Remove unnecessary git credentials
  jenkins/jobs/bml_integration_tests.pipeline
  jenkins/jobs/bmo_e2e_optional_tests.pipeline
  jenkins/jobs/capm3-e2e-tests.pipeline
  jenkins/jobs/clean_resources.pipeline
  jenkins/jobs/dev_env_integration_tests.pipeline
  jenkins/jobs/dynamic_fullstack_building.pipeline
  jenkins/jobs/e2e_features_test.pipeline
  jenkins/jobs/image_building.pipeline
Labels: size/M, approved, lgtm

#982 Bump openjdk to 17 in CI images
  jenkins/image_building/dib_elements/ci-base/package-installs.yaml
  jenkins/image_building/dib_elements/ci-base/pkg-map
Labels: size/XS, approved, lgtm

#983 Rotate authorized ssh key in images
  jenkins/image_building/authorized_keys
Labels: size/XS, approved, lgtm

#960 Enables optionally multiplatform container builds
  .github/workflows/container-image-build.yml
Labels: size/S, approved, lgtm, ok-to-test

#988 Image build job with test
  jenkins/image_building/build-image.sh
  jenkins/image_building/upload-ci-image.sh
  jenkins/image_building/verify-ci-image.sh
  jenkins/jobs/image_building.pipeline
  prow/config/jobs/metal3-io/project-infra.yaml
Labels: approved, lgtm, size/L

#989 Fix image build refspec for PR jobs
  jenkins/jobs/image_building.pipeline
Labels: size/XS, approved, lgtm

#993 bump golang to 1.24 for IRSO
  prow/config/jobs/metal3-io/ironic-standalone-operator.yaml
Labels: size/XS, approved, lgtm

#990 Fix image building refspec and upload
  jenkins/image_building/upload-ci-image.sh
  jenkins/jobs/image_building.pipeline
Labels: size/M, approved, lgtm

#992 Prow: Require manually triggered jobs
  prow/config/config.yaml
Labels: size/XS, approved, lgtm

#995 :seedling: Uplift Kubernetes version to v1.33.0 for image building
  jenkins/image_building/build-image.sh
Labels: size/XS, approved, lgtm

#994 Update CRIO installation link from k8s addons to CRI'o own subproject
  jenkins/image_building/dib_elements/centos-node/pre-install.d/55-setup-repos
  jenkins/image_building/dib_elements/ubuntu-node/pre-install.d/55-setup-repos
Labels: size/S, approved, lgtm

#997 Evaluate when block before agent in CI image verification
  jenkins/jobs/image_building.pipeline
Labels: size/XS, approved, lgtm

#996 Don't clean the yum cache while building CentOS node image
  jenkins/image_building/dib_elements/centos-node/pre-install.d/55-setup-repos
Labels: size/XS, approved, lgtm

#999 :seedling: Add CAPM3 release-1.10 to Prow
  prow/config/jobs/metal3-io/cluster-api-provider-metal3-release-1.10.yaml
Labels: approved, lgtm, size/L

#998 :seedling: Add IPAM release-1.10 to Prow
  prow/config/jobs/metal3-io/ip-address-manager-release-1.10.yaml
Labels: approved, lgtm, size/L

#1000 :seedling: Add BMO release-0.10 to Prow
  prow/config/jobs/metal3-io/baremetal-operator-release-0.10.yaml
Labels: approved, lgtm, size/L
